include $(GOROOT)/src/Make.$(GOARCH)

TARG=projecteuler
GOFILES=\
	problems.go\
	problem1.go\
	problem2.go\
	problem3.go\
	problem4.go\
	problem5.go\
	problem6.go\
	problem7.go\
	problem8.go\
	problem9.go\
	problem10.go\
	problem11.go\
	problem12.go\
	problem13.go\
	problem14.go\
	problem15.go\
	problem16.go\
	problem17.go\
	problem18.go\
	problem19.go\
	problem20.go\
	problem21.go\
	problem22.go\
	problem23.go\
	problem24.go\

include $(GOROOT)/src/Make.pkg
