include $(GOROOT)/src/Make.$(GOARCH)

TARG=projecteuler
GOFILES=\
	problems.go\
	problem1.go\
	problem2.go\
	problem3.go\
	problem4.go\
	problem5.go\
	problem6.go\
	problem7.go\
	problem8.go\
	problem9.go\
	problem10.go\

include $(GOROOT)/src/Make.pkg
