//Problem 29
//How many distinct terms are in the sequence generated by ab for 2  a  100 and 2  b  100?

package projecteuler

import (
	"fmt"
	"exp/bignum"
)

func Euler29()string{
	distinct := make(map[string]int)
	for a:=2;a<=100;a++{
		for b:=a;b<=100;b++{
			distinct[bignum.Nat(uint64(a)).Pow(uint(b)).String()]=0
			distinct[bignum.Nat(uint64(b)).Pow(uint(a)).String()]=0
		}
	}
	return fmt.Sprint(len(distinct))
}
