//Problem 29
//How many distinct terms are in the sequence generated by ab for 2  a  100 and 2  b  100?

package projecteuler

import (
	"fmt"
	"big"
	"bigextension"
)

func Euler29() string {
	distinct := make(map[string]int)
	for a := 2; a <= 100; a++ {
		for b := a; b <= 100; b++ {
			distinct[bigextension.Pow(big.NewInt(int64(a)), int64(b)).String()] = 0
			distinct[bigextension.Pow(big.NewInt(int64(b)), int64(a)).String()] = 0
		}
	}
	return fmt.Sprint(len(distinct))
}
